docs: add stateless redis disruptor proposal
grafana/xk6-disruptor pull request #331
Opened 2023-09-06 13:30 UTC by nadiamoe

# Description

This PR adds a proposal to add a redis disruptor. Details about the use cases and implementation proposals can be found in the added design doc.

2023-09-11 11:40 UTC, dgzlopes commented on docs/01-development/design-docs/003-stateless-redis-disruptor.md
> +| **Approver(s)**:        | Pablo Chacín (@pablochacin), Daniel Gonález (@dgzlopes) |
```suggestion
| **Approver(s)**:        | Pablo Chacín (@pablochacin), Daniel González (@dgzlopes) |
```

2023-09-12 09:43 UTC, roobre commented on docs/01-development/design-docs/003-stateless-redis-disruptor.md
> +| **Approver(s)**:        | Pablo Chacín (@pablochacin), Daniel Gonález (@dgzlopes) |
😅 🤦🏻‍♀️

2023-09-13 16:11 UTC, pablochacin requested changes
As I mentioned in my comments, I would prefer that we explore the stateful proxy as a goal and leave the stateless proxy as a PoC stage toward that goal as part of the implementation plan instead of as an alternative implementation.

The rationale for this is that the project should not aim for simple implementations but for meaningful developers experiences, and given the limitations of the stateless proxy, I'm not sure we would like to offer it to the users.

2023-09-13 16:11 UTC, pablochacin commented on docs/01-development/design-docs/003-stateless-redis-disruptor.md
> +- Easier to implement and less error-prone than a stateful proxy
I think that it is valid to implement a PoC using the stateless approach, but I would prefer that we address a full-fledged implementation in this design document.

2023-09-13 16:24 UTC, pablochacin commented
Regarding the complexity of implementing the Redis protocol, we can explore and learn from existing projects:
- https://github.com/Codility/redis-proxy
- https://github.com/segmentio/redis-go

2025-02-03 09:41 UTC, closed without merging